{
 "title": "Comparação entre Monolito e Microsserviços",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Mensagens MQTT processadas",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mqtt_messages_received_total{job=\"monolith\"}",
     "legendFormat": "Monolito"
    },
    {
     "expr": "mqtt_messages_received_total{job=\"ingestion-service\"}",
     "legendFormat": "Microsserviço - Ingestão"
    }
   ]
  },
  {
   "title": "Uso de memória",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_compose_service=~\"ingestion-service|mosquitto-exporter|notification-service|persistence-service|processing-service|rabbitmq\"})",
     "legendFormat": "Microsserviços"
    },
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_compose_service=\"monolith-app\"})",
     "legendFormat": "Monolito"
    }
   ]
  },
  {
   "title": "Registros salvos",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "persisted_records_total{job=\"monolith\"}",
     "legendFormat": "Monolito"
    },
    {
     "expr": "persisted_records_total{service=\"microservices\"}",
     "legendFormat": "Microsserviço - Persistência"
    }
   ]
  },
  {
   "title": "Mensagens processadas por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(mqtt_messages_received_total{job=\"monolith\"}[1m]))",
     "legendFormat": "Monolito"
    },
    {
     "expr": "sum(rate(mqtt_messages_received_total{job=\"ingestion-service\"}[1m]))",
     "legendFormat": "Microsserviço - Ingestão"
    }
   ]
  },
  {
   "title": "Tempo de processamento",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(processing_time_seconds_sum{service=\"monolith\"}[1m])\r\n/\r\nrate(processing_time_seconds_count{service=\"monolith\"}[1m])",
     "legendFormat": "Monolito"
    },
    {
     "expr": "max(rate(processing_time_seconds_sum{service=\"microservices\"}[1m])) / sum((rate(processing_time_seconds_count{service=\"microservices\"}[1m])))",
     "legendFormat": "Microsserviços"
    }
   ]
  },
  {
   "title": "Uso de CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{name=\"monolith-app\"}[1m])",
     "legendFormat": "Monolito"
    },
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"ingestion-service|processing-service|notification-service|persistence-service|rabbitmq\"}[1m]))",
     "legendFormat": "Microsserviços"
    }
   ]
  }
 ]
}