scrape_configs:
  - job_name: 'monolith'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:5004']


  - job_name: 'ingestion-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'processing-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:5001']

  - job_name: 'notification-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:5002']

  - job_name: 'persistence-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s # This can be adjusted based on our needs
    static_configs:
      - targets: ['host.docker.internal:5003']
      
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']